Kb/comment structure (#17) (#18)
* comment section complete. rendering comments with tree traversal to maintain comment section structure.

* working on getting the like functionality set up for comments. will require to rework backend routes to efficiently get the current user's liked comments

* fixed database query for comments and their replies so that it doesnt

* final adjustments to the route after further testing

* quick fix to post route for a missing joinedload

* safety commit

* updating other routes so that they have joinedload

* edit to comment

* safety comit

* fixing yaml file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,14 +9,10 @@ jobs:
   check-branch:
     runs-on: ubuntu-latest
     steps:
-      - name: Check PR source
+      - name: Check branch
         run: |
-          if [[ ${GITHUB_HEAD_REF} != staging ]];
-            then
-<<<<<<< HEAD
-              echo "Error: Pull request to the 'main' branch must come from 'staging' branch"
-=======
-              echo "Error: Pull requests to the 'main' branch must come from 'staging' branch"
->>>>>>> staging
-              exit 1
-            fi
+          if [[ ${GITHUB_HEAD_REF} != staging ]]; 
+          then
+            echo "Error: Pull request must come from 'staging' branch"
+            exit 1
+          fi
